"""Константы приложения Talker Box"""

# Размеры окон
WINDOW_WIDTH = 585
WINDOW_HEIGHT = 419
CIRCLE_SIZE = 200
MASCOT_SIZE = 80
SIGNAL_LABEL_WIDTH = 180
SIGNAL_VALUE_HEIGHT = 36

# Размеры элементов
LOGO_SIZE = 32
HEADER_BTN_SIZE = 36
ICON_CONTAINER_SIZE = 44
CHECKBOX_SIZE = 14

# Тайминги (мс)
SIGNAL_TIMER_INTERVAL = 1500
AD_TIMER_INTERVAL = 60000

# Кнопки панели
BOTTOM_BTN_WIDTH = 150
BOTTOM_BTN_HEIGHT = 40
